version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql:z
    env_file: config.txt


  app:
    image: nextcloud:fpm
    restart: always
    links:
      - db
    volumes:
      - ./nextcloud:/var/www/html:z
    env_file: config.txt
    ports:
      - 19980:80

# Assuming NGINX instance is already running, proxy to 19980
